// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyZZ4qhjKocyb5ITlyUtvqm6SaCnotdqU',
    appId: '1:266380105310:web:b2220673f8d02e408846cf',
    messagingSenderId: '266380105310',
    projectId: 'hotelio-9d810',
    authDomain: 'hotelio-9d810.firebaseapp.com',
    storageBucket: 'hotelio-9d810.appspot.com',
    measurementId: 'G-LSFCJCZBFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs9KzWyh_yGSMWAGKQ5wWcM72gBBKRyCw',
    appId: '1:266380105310:android:1bda0d0770635b868846cf',
    messagingSenderId: '266380105310',
    projectId: 'hotelio-9d810',
    storageBucket: 'hotelio-9d810.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5OXqpCVSmdxDu9FCzr1PcGnPt5fAEwus',
    appId: '1:266380105310:ios:923816f2064b1bc68846cf',
    messagingSenderId: '266380105310',
    projectId: 'hotelio-9d810',
    storageBucket: 'hotelio-9d810.appspot.com',
    iosClientId: '266380105310-b6epc1kb7tqsjpa6nr6te6guq43nvov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5OXqpCVSmdxDu9FCzr1PcGnPt5fAEwus',
    appId: '1:266380105310:ios:923816f2064b1bc68846cf',
    messagingSenderId: '266380105310',
    projectId: 'hotelio-9d810',
    storageBucket: 'hotelio-9d810.appspot.com',
    iosClientId: '266380105310-b6epc1kb7tqsjpa6nr6te6guq43nvov9.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );
}
